### ISSUE TITLE
Exception's thrown when trying to embed a map from a non-existent title

### ISSUE THREAD

**Issue by alex4401** [alex4401/mediawiki-extensions-DataMaps#259]

**Comment by GoboZen** [comment]
Same issue, here's the stacktrace. Reproducing is easy: I moved (renamed) an entry in the Map: namespace. Opening a page with a transclude to that Map throws this exception.
```
Internal error
Jump to navigationJump to search
[cf953b4bfc66a76d9aeeef5c] /wiki/Saline_Quarry Error: Call to a member function getId() on null

Backtrace:

from /var/www/wiki/extensions/DataMaps/includes/ParserFunctions/EmbedMapFunction.php(40)
#0 /var/www/wiki/includes/parser/Parser.php(3437): MediaWiki\Extension\DataMaps\ParserFunctions\EmbedMapFunction::run()
#1 /var/www/wiki/includes/parser/Parser.php(3122): Parser->callParserFunction()
#2 /var/www/wiki/includes/parser/PPFrame_Hash.php(275): Parser->braceSubstitution()
#3 /var/www/wiki/includes/parser/Parser.php(2951): PPFrame_Hash->expand()
#4 /var/www/wiki/includes/parser/Parser.php(1609): Parser->replaceVariables()
#5 /var/www/wiki/includes/parser/Parser.php(723): Parser->internalParse()
#6 /var/www/wiki/includes/content/WikitextContentHandler.php(301): Parser->parse()
#7 /var/www/wiki/includes/content/ContentHandler.php(1721): WikitextContentHandler->fillParserOutput()
#8 /var/www/wiki/includes/content/Renderer/ContentRenderer.php(47): ContentHandler->getParserOutput()
#9 /var/www/wiki/includes/Revision/RenderedRevision.php(266): MediaWiki\Content\Renderer\ContentRenderer->getParserOutput()
#10 /var/www/wiki/includes/Revision/RenderedRevision.php(237): MediaWiki\Revision\RenderedRevision->getSlotParserOutputUncached()
#11 /var/www/wiki/includes/Revision/RevisionRenderer.php(221): MediaWiki\Revision\RenderedRevision->getSlotParserOutput()
#12 /var/www/wiki/includes/Revision/RevisionRenderer.php(158): MediaWiki\Revision\RevisionRenderer->combineSlotOutput()
#13 [internal function]: MediaWiki\Revision\RevisionRenderer->MediaWiki\Revision\{closure}()
#14 /var/www/wiki/includes/Revision/RenderedRevision.php(199): call_user_func()
#15 /var/www/wiki/includes/poolcounter/PoolWorkArticleView.php(91): MediaWiki\Revision\RenderedRevision->getRevisionParserOutput()
#16 /var/www/wiki/includes/poolcounter/PoolWorkArticleViewCurrent.php(97): PoolWorkArticleView->renderRevision()
#17 /var/www/wiki/includes/poolcounter/PoolCounterWork.php(162): PoolWorkArticleViewCurrent->doWork()
#18 /var/www/wiki/includes/page/ParserOutputAccess.php(299): PoolCounterWork->execute()
#19 /var/www/wiki/includes/page/Article.php(714): MediaWiki\Page\ParserOutputAccess->getParserOutput()
#20 /var/www/wiki/includes/page/Article.php(528): Article->generateContentOutput()
#21 /var/www/wiki/includes/actions/ViewAction.php(78): Article->view()
#22 /var/www/wiki/includes/MediaWiki.php(542): ViewAction->show()
#23 /var/www/wiki/includes/MediaWiki.php(322): MediaWiki->performAction()
#24 /var/www/wiki/includes/MediaWiki.php(904): MediaWiki->performRequest()
#25 /var/www/wiki/includes/MediaWiki.php(562): MediaWiki->main()
#26 /var/www/wiki/index.php(50): MediaWiki->run()
#27 /var/www/wiki/index.php(46): wfIndexMain()
#28 {main}
```
